module HttpStatusCodes
    HTTP_OK_CODE = 200

    HTTP_BAD_REQUEST_CODE = 400
    HTTP_UNAUTHORIZED_CODE = 401
    HTTP_FORBIDDEN_CODE = 403
    HTTP_NOT_FOUND_CODE = 404
    HTTP_METHOD_NOT_ALLOWED_CODE = 405
    HTTP_NOT_ACCEPTABLE_CODE = 406
    HTTP_CONFLICT_CODE = 409
    HTTP_GONE_CODE = 410
    HTTP_UNPROCESSABLE_ENTITY_CODE = 422
    HTTP_TOO_MANY_REQUESTS_CODE = 429
    
end